### ISSUE TITLE
ConsiderAddingWiseOlderBrotherCharacterNamedAlex

### ISSUE THREAD

**Issue by nikymorg** [RachelSa/make-alex-famous-book#5]
![bitmoji](https://render.bitstrips.com/v2/cpanel/2cf31ca6-448d-4d41-a200-1e7d821d037e-9193779d-d76d-402b-9ad9-9a3783642625-v1.png?transparent=1&palette=1&width=246)
cc:
@RachelSa 
@alexgriff 
@realAndrewCohn
@danielseehausen

**Comment by DanielSeehausen** [comment]
just wanted to revive the request:

@RachelSa
@alexgriff
@realAndrewCohn
@nikymorg

**Comment by DanielSeehausen** [comment]
> Rake pulled the currents shut
> A superficial attempt to make them a 'them'
> and him a lonely 'us'.
> He hid his disgust as well as the curtain blocked their bickering

@alexgriff for the book

**Comment by realAndrewCohn** [comment]
lets make it happen

**Comment by nikymorg** [comment]
Sorry, closed this in #11 and forgot to update.
